/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppCountInput: typeof import('./src/components/AppCountInput.vue')['default']
    AppModalOverlay: typeof import('./src/components/AppModalOverlay.vue')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    CartWidget: typeof import('./src/components/CartWidget.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
